<?php declare(strict_types=1);

/**
 * Datince - REST API
 * REST API for Datince.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: avbaryshev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface GoalsApiInterface {


    /**
     * Operation filtersWithGoalsGet
     *
     * Get user filters with goals
     * @return \OpenAPI\Server\Model\FiltersWithGoals
     */
    public function filtersWithGoalsGet(
    ):
        \OpenAPI\Server\Model\FiltersWithGoals
    ;


    /**
     * Operation filtersWithGoalsPut
     *
     * Update user filters with goals
     * @param null | \OpenAPI\Server\Model\FiltersWithGoals $filtersWithGoals
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function filtersWithGoalsPut(
            ?\OpenAPI\Server\Model\FiltersWithGoals $filtersWithGoals,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;


    /**
     * Operation goalsGet
     *
     * Get user goals
     * @return \OpenAPI\Server\Model\GoalList
     */
    public function goalsGet(
    ):
        \OpenAPI\Server\Model\GoalList
    ;


    /**
     * Operation goalsPut
     *
     * Update all goals
     * @param null | \OpenAPI\Server\Model\GoalList $goalList
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function goalsPut(
            ?\OpenAPI\Server\Model\GoalList $goalList,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;

}
