<?php declare(strict_types=1);

/**
 * Datince - REST API
 * REST API for Datince.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: avbaryshev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * ChatList
 */
namespace OpenAPI\Server\Model;

/**
 * ChatList
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class ChatList
{
    /**
    *
    * 
    * @param int $id
    *
    * 
    * @param \OpenAPI\Server\Model\User $user
    */

    public function __construct(
        public int $id,
        public \OpenAPI\Server\Model\User $user,
    ) {}
}

