<?php declare(strict_types=1);

/**
 * Datince - REST API
 * REST API for Datince.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: avbaryshev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Message
 */
namespace OpenAPI\Server\Model;

/**
 * Message
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Message
{
    /**
    *
    * 
    * @param string $id
    *
    * 
    * @param string $type
    *
    * 
    * @param string $text
    *
    * 
    * @param string $senderId
    *
    * 
    * @param string $receiverId
    *
    * 
    * @param string $timestamp
    *
    * 
    * @param string $status
    */

    public function __construct(
        public string $id,
        public string $type,
        public string $text,
        public string $senderId,
        public string $receiverId,
        public string $timestamp,
        public string $status,
    ) {}
}

