<?php declare(strict_types=1);

/**
 * Datince - REST API
 * REST API for Datince.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: avbaryshev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface AuthApiInterface {


    /**
     * Operation authForgotPasswordPost
     *
     * Initiate password reset
     * @param null | \OpenAPI\Server\Model\AuthForgotPasswordPostRequest $authForgotPasswordPostRequest
     * @return \OpenAPI\Server\Model\NoContent202
     */
    public function authForgotPasswordPost(
            ?\OpenAPI\Server\Model\AuthForgotPasswordPostRequest $authForgotPasswordPostRequest,
    ):
        \OpenAPI\Server\Model\NoContent202
    ;


    /**
     * Operation authLoginPost
     *
     * User login
     * @return \OpenAPI\Server\Model\NoContent200 | \OpenAPI\Server\Model\ErrorResponse
     */
    public function authLoginPost(
    ):
        \OpenAPI\Server\Model\NoContent200 | 
        \OpenAPI\Server\Model\ErrorResponse
    ;


    /**
     * Operation authLogoutPost
     *
     * User logout
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function authLogoutPost(
    ):
        \OpenAPI\Server\Model\NoContent200
    ;


    /**
     * Operation authRegisterPost
     *
     * Register new user
     * @param null | \OpenAPI\Server\Model\UserRegistration $userRegistration
     * @return \OpenAPI\Server\Model\User
     */
    public function authRegisterPost(
            ?\OpenAPI\Server\Model\UserRegistration $userRegistration,
    ):
        \OpenAPI\Server\Model\User
    ;


    /**
     * Operation authResetPasswordPost
     *
     * Complete password reset
     * @param null | \OpenAPI\Server\Model\AuthResetPasswordPostRequest $authResetPasswordPostRequest
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function authResetPasswordPost(
            ?\OpenAPI\Server\Model\AuthResetPasswordPostRequest $authResetPasswordPostRequest,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;


    /**
     * Operation authVerifyEmailPost
     *
     * Verify email address
     * @param null | \OpenAPI\Server\Model\AuthVerifyEmailPostRequest $authVerifyEmailPostRequest
     * @return \OpenAPI\Server\Model\NoContent200
     */
    public function authVerifyEmailPost(
            ?\OpenAPI\Server\Model\AuthVerifyEmailPostRequest $authVerifyEmailPostRequest,
    ):
        \OpenAPI\Server\Model\NoContent200
    ;

}
