<?php declare(strict_types=1);

/**
 * Datince - REST API
 * REST API for Datince.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: avbaryshev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface ChatApiInterface {


    /**
     * Operation chatChatIdGet
     *
     * Chat messages
     * @param string $chatId
     * @return \OpenAPI\Server\Model\ChatMessages
     */
    public function chatChatIdGet(
            string $chatId,
    ):
        \OpenAPI\Server\Model\ChatMessages
    ;


    /**
     * Operation chatGet
     *
     * Chat list with users
     * @return \OpenAPI\Server\Model\ChatList
     */
    public function chatGet(
    ):
        \OpenAPI\Server\Model\ChatList
    ;

}
