<?php declare(strict_types=1);

/**
 * Datince - REST API
 * REST API for Datince.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 2.0.6
 * Contact: avbaryshev@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface LocationsApiInterface {


    /**
     * Operation locationsDefaultGet
     *
     * Get default location
     * @return \OpenAPI\Server\Model\Location | \OpenAPI\Server\Model\ErrorResponsePlace
     */
    public function locationsDefaultGet(
    ):
        \OpenAPI\Server\Model\Location | 
        \OpenAPI\Server\Model\ErrorResponsePlace
    ;


    /**
     * Operation locationsLocationIdDelete
     *
     * Delete location
     * @param string $locationId
     * @return \OpenAPI\Server\Model\NoContent204
     */
    public function locationsLocationIdDelete(
            string $locationId,
    ):
        \OpenAPI\Server\Model\NoContent204
    ;


    /**
     * Operation locationsLocationIdGet
     *
     * Get specific location
     * @param string $locationId
     * @return \OpenAPI\Server\Model\Location
     */
    public function locationsLocationIdGet(
            string $locationId,
    ):
        \OpenAPI\Server\Model\Location
    ;


    /**
     * Operation locationsLocationIdPatch
     *
     * Update location status
     * @param string $locationId
     * @param null | \OpenAPI\Server\Model\LocationsLocationIdPatchRequest $locationsLocationIdPatchRequest
     * @return \OpenAPI\Server\Model\NoContent200 | \OpenAPI\Server\Model\ErrorResponsePlace
     */
    public function locationsLocationIdPatch(
            string $locationId,
            ?\OpenAPI\Server\Model\LocationsLocationIdPatchRequest $locationsLocationIdPatchRequest,
    ):
        \OpenAPI\Server\Model\NoContent200 | 
        \OpenAPI\Server\Model\ErrorResponsePlace
    ;

}
